<?php function printComment($comment, &$comments, $childrens, $authUser) { ?>
    <div class="comment" id="comment_<?=$comment->id?>">
        <img src="<?=$comment->user->avatar?>" alt="<?=$comment->user->name?>" />
        <span class="name"><?=$comment->user->name?></span>
        <span class="date"><?=$comment->date?></span>
        <p class="text"><?=$comment->text?></p>
        <div class="clear"></div>
        <p class="functions"><span <?php if (!$authUser) { ?>
                onclick="alert('Для добавления комментариев необходимо авторизоваться на сайте!')"
            <?php } else { ?>class="reply_comment"<?php } ?>>Ответить</span>
            <?php if ($authUser) { ?><?php if ($comment->accessEdit($authUser, "text")) { ?>
                <span class="edit_comment">Редактировать</span>
            <?php } if ($comment->accessDelete($authUser)) { ?>
                <span class="delete_comment">Удалить</span><?php } ?><?php } ?>
        </p>
        <?php
        while (true) {
            $key = array_search($comment->id, $childrens);
            if (!$key) break;
            unset($childrens[$key]);
            ?>
            <?php if (isset($comments[$key])) { ?>
                <?=printComment($comments[$key], $comments, $childrens, $authUser)?>
            <?php } ?>
        <?php } ?>
    </div>
<?php } ?>
<div class="main">
    <?php if (isset($hornav)) { ?><?=$hornav?><?php } ?>
    <article>
        <h1><?=$article->title?></h1>
        <?php if ($article->img) { ?>
            <div class="article_img">
                <img src="<?=$article->img?>" alt="<?=$article->title?>" />
            </div>
        <?php } ?>
        <?=$article->full?>
        <div class="article_info">
            <ul>
                <li>
                    <span>
                        <img src="/images/date_article.png" alt="" />
                    </span>
                    Создано <?=$article->date?>
                </li>
                <li>
                    <img src="/images/icon_user.png" alt="" />
					Alex_R
                </li>
            </ul>
            <div class="clear"></div>
        </div>
    </article>
    <div id="article_pn">
        <?php if ($prevArticle) { ?><a id="prev_article" href="<?=$prevArticle->link?>">Предыдущая статья</a><?php } ?>
        <?php if ($nextArticle) { ?><a id="next_article" href="<?=$nextArticle->link?>">Следующая статья</a><?php } ?>
        <div class="clear"></div>
    </div>
    <div id="comments">
        <h2 class="h1">Комментарии (<span id="count_comments"><?=count($comments)?></span>):</h2>
		<div id="share">
			<p>Порекомендуйте эту статью друзьям:</p>
			<script type="text/javascript">getSocialNetwork("<?=\library\config\Config::DIR_IMG?>", "");</script>
		</div>
        <input type="button" value="Добавить комментарий" id="add_comment" <?php if (!$authUser) { ?>onclick="alert('Для добавления комментариев необходимо авторизоваться на сайте!')"<?php } ?> />
        <?php foreach ($comments as $comment) { ?>
            <?php if ($comment->parentId == 0) { ?><?=printComment($comment, $comments, $childrens, $authUser)?><?php } ?>
        <?php } ?>
        <div class="clear"></div>
        <?php if ($authUser) { ?>
            <div id="form_add_comment">
                <form name="form_add_comment" method="post" action="#">
                    <div id="comment_cancel">
                        <span>X</span>
                    </div>
                    <table>
                        <tr>
                            <td>
                                <label for="text_comment">Комментарий:</label>
                            </td>
                            <td>
                                <textarea cols="40" rows="5" name="text_comment" id="text_comment"></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
							<input type="hidden" value="0" name="comment_id" id="comment_id" />
                            <input type="hidden" value="<?=$article->id?>" name="article_id" id="article_id" />
                            <input type="hidden" value="0" name="parent_id" id="parent_id" />
                            <input type="button" value="Сохранить" class="button" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        <?php } else { ?>
            <p class="center">Для добавления комментариев надо войти в систему.<br />Если Вы ещё не зарегистрированы на сайте, то сначала <a href="<?=$linkRegister?>">зарегистрируйтесь</a>.</p>
        <?php } ?>
    </div>
</div>