<?php foreach($courses as $course) { ?>
<div class="block">
    <div class="header"><?=$course->header?></div>
    <div class="content">
        <div class="free">
            <p class="title"><?=$course->subheader?></p>
            <a href="<?=$course->link?>">
            <img src="<?=$course->img?>" alt="<?=$course->title?>">
            </a>
            <?=$course->text?>

            <?php if($course->did) : ?>
            <p class="center"><b>Чтобы получить видеокурс <br> заполните форму</b></p>
            <form name="free_course" action="#" method="post">
                <table>
                    <tr>
                        <td>
                            <label for="free_course_email">E-mail: </label>
                        </td>
                        <td>
                            <input id="free_course_email" type="email" name="email" value="<?=is_null($authUser) ? '' : $authUser->email?>">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="free_course_name">Имя: </label>
                        </td>
                        <td>
                            <input id="free_course_name" type="text" name="name" value="<?=is_null($authUser) ? '' : $authUser->name?>">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="center">
                            <input type="hidden" value="1" name="version">
                            <input type="hidden" value="187271" name="tid">
                            <input type="hidden" value="85884" name="uid">
                            <input type="hidden" value="ru" name="lang">
                            <input type="hidden" value="<?=$course->did?>" name="did[]">
                            <input type="submit" name="free_course" class="button" value="Запросить курс">
                        </td>
                    </tr>
                </table>
            </form>

            <?php else : ?>
            <div class="center">
                <a href="<?=$course->link?>" class="button">Записаться</a>
            </div>
            <?php endif; ?>

        </div>
    </div>
</div>
<?php } ?>