<div class="block">
    <div class="header">Опрос</div>
    <div class="content">
        <div id="poll">
            <p><?=$title?></p>
            <form name="poll" action="<?=$action?>" method="post">
                <?php foreach ($data as $poll) { ?>
                    <div>
                        <input id="poll_id_<?=$poll->id?>" type="radio" name="poll" value="<?=$poll->id?>">
                        <label for="poll_id_<?=$poll->id?>"><?=$poll->title?></label>
                    </div>
                <?php } ?>
                <div>
                    <input type="submit" value="Проголосовать" class="button" name="poll">
                </div>
            </form>
        </div>
    </div>
</div>