<div class="block">
    <div class="header">Опрос</div>
    <div class="content">
        <div id="pool">
            <p><?=$title?></p>
            <form name="pool" action="<?=$action?>" method="post">
                <?php foreach ($data as $pool) { ?>
                    <div>
                        <input id="pool_id_<?=$poll->id?>" type="radio" name="pool" value="<?=$poll->id?>">
                        <label for="pool_id_<?=$poll->id?>"><?=$poll->title?></label>
                    </div>
                <?php } ?>
                <div>
                    <input type="submit" value="Проголосовать" class="button" name="pool">
                </div>
            </form>
        </div>
    </div>
</div>